### PR TITLE
the speedometer disappears

### PR DESCRIPTION
**Pull request by lush0n3**
If you get on a bike, the speedometer is no longer displayed.

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi! That's on purpose. Ask @Rav3n95.

**Comment by Rav3n95** [comment]
Wh whould you have a Speedo whit rpm on a BMX?

**Comment by lush0n3** [comment]
That is, this command line makes the speedometer not appear in any other type of vehicle, after getting on a bmx or bicycle.

**Comment by Gellipapa** [comment]
@lush0n3  #6 Thank you for report this issue.

**Pull request closed without merging**
