### PR TITLE
style(esx_hud): run prettier

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Gellipapa** [comment]
Hi! @MoskalykA Thank you for help but one or two places where the formatting is wrong I have to check it again.
image

**Comment by MoskalykA** [comment]
> Hi! @MoskalykA Thank you for help but one or two places where the formatting is wrong I have to check it again. image

I don't see this either on Github or on VSCode

**Comment by Gellipapa** [comment]
@MoskalykA Hi! Thank you for answer, hm that's weird, I'll have a look in local.

**Comment by Gellipapa** [comment]
@MoskalykA Thank you for pr, i closed your merge because lot of merge conflict and new release i will run prettier all repos.

**Pull request closed without merging**
