### PR TITLE
Add french translation

### PR DESCRIPTION
**Pull request by Slewog**
Hello, just a little PR to implement french translations into the HUD

### CODE REVIEW

**Review by Thekuca — CHANGES_REQUESTED** [review]
fix conflict

**Comment by Slewog** [comment]
I have a conflict for the missing comment or for the variable added in the config? Because without it it does not change the translations on the lua side

**Comment by Slewog** [comment]
> fix conflict

i fixed all conflict i think

**Review by Thekuca — APPROVED** [review]

**Comment by Gellipapa** [comment]
@Slewog  #50 Add this pr. Thank you for help.

**Pull request closed without merging**
